MoonpaperLinux/Models/Article.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.Threading.Tasks;


namespace MoonpaperLinux.Models
{
    public class Article
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public Source Source { get; set; }
        public string Url { get; set; }
        public string UrlMainImg { get; set; }
        public int Views { get; set; }
        public int Stars { get; set; }

        public List<ArticleTag> ArticleTags { get; set; }

        public DateTime DateTime { get; set; }

        public Article()
        {
            ArticleTags = new List<ArticleTag>();
            Source = new Source();
        }
    }
}

MoonpaperLinux/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using MoonpaperLinux.Models;
using MoonpaperLinux.ViewModels;

namespace MoonpaperLinux.Controllers
{

    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получение списка ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получение списка ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получение ролей
                var allRoles = _roleManager.Roles.ToList();
                // получение списока ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получение ролей, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

MoonpaperLinux/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using MoonpaperLinux.Models;
using MoonpaperLinux.ViewModels;

namespace MoonpaperLinux.Controllers
{

    [Authorize(Roles = "admin")]
    public class UsersController : Controller
    {

        UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email};
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email};
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
    }
}

MoonpaperLinux/Views/Shared/_Articles.cshtml
@foreach (var item in ViewBag.ArticlePersonals)
{
    <div class="block__item_line">
        <a href="@item.Url" target="_blank"><img src="@item.UrlMainImg" alt="@item.Title" class="article-img"></a>
        <div class="text">
            <h2><a href="@item.Url" target="_blank" class="text__title">@item.Title</a></h2>
            <div class="text__summary">
                @item.Summary
            </div>
        </div>
        <div class="tags-info">
            <div class="tags">
                <div class="tags__Line">
                </div>
                <div id="displayable" class="tags__Drop">
                    <div class="tags__Drop_panel">
                        <div class="tags__icon"></div>
                        <div class="tag">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a href="@item.Source.Url" class="tag__name @if (item.SourceRating > 0) {<text>active</text>} @if (item.SourceRating < 0) {<text>disactive</text>}">@item.Source.Name</a>
                                <form class="tag__btn-off @if (item.SourceRating < 0) {<text>active</text>}" method="post" data-ajax="true" data-ajax-method="post" asp-controller="Home" asp-action="SourceDown">
                                    <input name="UserId" type="hidden" value="@ViewBag.UserId">
                                    <input name="SourceId" type="hidden" value="@item.Source.Id">
                                    <input class="submit_tagOff submit" type="submit" value="" />
                                </form>
                                <form class="tag__btn-on @if (item.SourceRating > 0) {<text>active</text>}" method="post" data-ajax="true" data-ajax-method="post" asp-controller="Home" asp-action="SourceUp">
                                    <input name="UserId" type="hidden" value="@ViewBag.UserId">
                                    <input name="SourceId" type="hidden" value="@item.Source.Id">
                                    <input class="submit_tagOn submit" type="submit" value="" />
                                </form>
                            }
                            else
                            {
                                <a href="@item.Source.Url" class="tag__name">@item.Source.Name</a>
                                <a href="/Identity/Account/Register" class="tag__btn-off"></a>
                                <a href="/Identity/Account/Register" class="tag__btn-on"></a>
                            }
                        </div>
                        @{
                            if (item.ArticleTagPersonals != null)
                            {
                                foreach (var tag in item.ArticleTagPersonals)
                                {
                                    <div class="tag">
                                        @if (User.Identity.IsAuthenticated)
                                        {
                                            <a href="/Home/Tag?tag=@tag.Tag.TagValue" class="tag__name @if (tag.Rating > 0) {<text>active</text>} @if (tag.Rating < 0) {<text>disactive</text>}">@tag.Tag.TagValue</a>
                                            <form class="tag__btn-off @if (tag.Rating < 0) {<text>active</text>}" method="post" data-ajax="true" data-ajax-method="post" asp-controller="Home" asp-action="TagDown">
                                                <input name="UserId" type="hidden" value="@ViewBag.UserId">
                                                <input name="TagId" type="hidden" value="@tag.Tag.Id">
                                                <input class="submit_tagOff submit" type="submit" value="" />
                                            </form>
                                            <form class="tag__btn-on @if (tag.Rating > 0) {<text>active</text>}" method="post" data-ajax="true" data-ajax-method="post" asp-controller="Home" asp-action="TagUp">
                                                <input name="UserId" type="hidden" value="@ViewBag.UserId">
                                                <input name="TagId" type="hidden" value="@tag.Tag.Id">
                                                <input class="submit_tagOn submit" type="submit" value="" />
                                            </form>
                                        }
                                        else
                                        {
                                            <a href="/Home/Tag?tag=@tag.Tag.TagValue" class="tag__name">@tag.Tag.TagValue</a>
                                            <a href="/Identity/Account/Register" class="tag__btn-off"></a>
                                            <a href="/Identity/Account/Register" class="tag__btn-on"></a>
                                        }
                                    </div>
                                }
                            }
                        }
                    </div>
                </div>
            </div>
            <div class="info">
                <div class="info__block">
                    <div class="info__time">
                        @Helper.GetTimeForArticle(item.DateTime)
                    </div>
                    <div class="info__views">
                        @item.Views
                    </div>
                </div>
                <div class="info__block-star">
                    <div class="info__stars">@item.Stars</div>
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (item.IsStar)
                        {
                            <form class="info__stars-button active" method="post" data-ajax="true" data-ajax-method="post" asp-controller="Home" asp-action="StarDown">
                                <input name="UserId" type="hidden" value="@ViewBag.UserId">
                                <input name="ArticleId" type="hidden" value="@item.Id">
                                <input id="star" class="starClick submit" type="submit" value="" />
                            </form>
                        }
                        else
                        {
                            <form class="info__stars-button" method="post" data-ajax="true" data-ajax-method="post" asp-controller="Home" asp-action="StarUp">
                                <input name="UserId" type="hidden" value="@ViewBag.UserId">
                                <input name="ArticleId" type="hidden" value="@item.Id">
                                <input id="star" class="starClick submit" type="submit" value="" />
                            </form>
                        }
                    }
                    else
                    {
                        <a href="/Identity/Account/Register" class="info__stars-button"></a>
                    }
                    @*<a href="#" class="info__stars-button"></a>*@
                </div>
            </div>
        </div>
        <div class="info__block" id="double">
            <div class="info__time">
                @Helper.GetTimeForArticle(item.DateTime)
            </div>
            <div class="info__views">
                @item.Views
            </div>
        </div>
    </div>
}

MoonpaperLinux/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width">
    <meta name="description" content="Moonpaper - это агрегатор новостей который каждый может настроить под себя. Мы не скрываем количество просмотров и лайков у новостей, поэтому принципы по которым формируется лента новостей остается прозрачной и честной для Вас.">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <script type="text/javascript">(function (m, e, t, r, i, k, a) { m[i] = m[i] || function () { (m[i].a = m[i].a || []).push(arguments) }; m[i].l = 1 * new Date(); k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a) })(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(67506880, "init", { clickmap: true, trackLinks: true, accurateTrackBounce: true, webvisor: true, trackHash: true });</script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-179037681-1"></script>
    <script> window.dataLayer = window.dataLayer || []; function gtag() { dataLayer.push(arguments); } gtag('js', new Date()); gtag('config', 'UA-179037681-1');</script>
</head>
<body>
    <noscript><div><img src="https://mc.yandex.ru/watch/67506880" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <div class="container">
        <div class="wrapper">
            <header>
                <a class="block_left" asp-area="" asp-controller="Home" asp-action="All">
                    <div><img src="~/img/logo.png" alt="" class="logo"></div>
                </a>
                <div class="block_right">
                    <div class="find">
                        <form method="get" asp-controller="Home" asp-action="Search">
                            <input type="text" name="Query" placeholder="Поиск">
                            <input type="hidden" name="SortedBy" value="@ViewBag.SortedBy">
                            <input type="hidden" name="Time" value="@ViewBag.Time">
                            <input type="hidden" name="Pages" value="@ViewBag.Pages">
                            <button type="submit"></button>
                        </form>
                        <div class="find-img">
                            <img src="~/img/icons/i_search_gray.png" alt="">
                        </div>
                    </div>
                    <div class="start">
                        <div href="" class="start__button">
                            <img src="~/img/icons/i_rocket_gray.png" alt="" class="start__img">
                        </div>
                        <div class="side-menu">
                            <div class="side-menu__name">МЕНЮ</div>
                            <div class="side-menu__block">
                                <partial name="_LoginPartial" />
                                @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                                {
                                    <div class="side-menu__item">
                                        <a class="link" asp-area="" asp-controller="Users" asp-action="Index">Пользователи</a>
                                    </div>
                                    <div class="side-menu__item">
                                        <a class="link" asp-area="" asp-controller="Roles" asp-action="Index">Роли</a>
                                    </div>
                                }
                            </div>
                            <div class="side-menu__block_last">
                                <div class="side-menu__item">
                                    <a class="link" href="#">О сайте</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            @RenderBody()
        </div>
    </div>
    <a id="button_rise"></a>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>